services:
  serve:
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    ports:
      - "8000:8000"
    command: serve --dev-addr 0.0.0.0:8000
  
  build:
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    command: build